topics:
-
  name    : joy_teleop/cmd_vel
  topic   : joy_teleop/cmd_vel
  timeout : 1.5
  priority: 50
-
  name    : maker
  topic   : cmd
  timeout : 0.5
  priority: 10
-
  name    : common
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
-
  name    : tablet
  topic   : tab_vel
  timeout : 0.5
  priority: 100
locks:
-
  name    : darpa_estop
  topic   : emergency_stop 
  timeout : 10000.0
  priority: 100
